### ISSUE TITLE
Creating FDW Server with multiple Tables

### ISSUE THREAD

**Issue by ratheesh-kr** [wjch-krl/pgCassandra#1]
I have two tables in Cassandra - activity1 and activity2,

I already created two servers using the following queries

CREATE SERVER server_activity1 FOREIGN DATA WRAPPER multicorn options (
wrapper 'pgCassandra.CassandraFDW',
port '9042',
columnfamily 'activity1',
keyspace 'keyspace',
hosts '192.168.1.1'
);

which is working fine for us, but when I want to connect with the second table here I need to create another server?

CREATE SERVER server_activity2 FOREIGN DATA WRAPPER multicorn options (
wrapper 'pgCassandra.CassandraFDW',
port '9042',
columnfamily 'activity2,
keyspace 'keyspace',
hosts '192.168.1.1'
);

OR Can we use the same server for both the tables (columnfamily)?

Some one pls advice.

**Comment by wjch-krl** [comment]
Yes currently you have to create two separate servers. However I am planning to implement this in the future (Next weekend).

**Comment by ratheesh-kr** [comment]
Thax for your reply.. we are  waiting for that :)

**Comment by ratheesh-kr** [comment]
Any Update from your end :)

**Comment by wjch-krl** [comment]
Sorry for late reply, but I've been really busy.
It have been working all along :), but I've just newer tested it (and I have written the code few moths ago, so I didn't remember).

Settings set on create table overrides one set on server.
I will update readme with this example:

```
CREATE SERVER multicorn_srv FOREIGN DATA WRAPPER multicore
options (
  wrapper 'pgCassandra.CassandraFDW',
   port '9042',
   hosts '127.0.0.1'
);

CREATE FOREIGN TABLE test (
    id text,
    message text
)
SERVER multicorn_srv options (
   columnfamily 'test',
   keyspace 'demo'
);

CREATE FOREIGN TABLE test2 (
    id2 text,
    message2 text,
)
SERVER multicorn_srv options (
   columnfamily 'test2',
   keyspace 'demo'
);
```

**Comment by ratheesh-kr** [comment]
Thanks for the Reply ... !!!
