### ISSUE TITLE
PostgreSQL version Update

### ISSUE THREAD

**Issue by ratheesh-kr** [wjch-krl/pgCassandra#3]
We updated the PostgreSQL version 9.5.0 to 9.5.1,
We face an issue while querying, we got an error as follows

`server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
Failed.`

Can you please help.

**Comment by wjch-krl** [comment]
Have you tried reinstalling Multicorn and pgCassandra ?

**Comment by ratheesh-kr** [comment]
Hi,

We checked this in three differnent senarios.
1. Installed  the PG cassandra and multicron in a fresh postgre 9.5.1 server
2. Upgrade the postgreSQL 9.5.1 from 9.5.0
3. removed  and reinstall the pg casandra and multicron 

but for all this cases, the issue  still there

**Comment by wjch-krl** [comment]
For me it looks like multicorn is not working properly with Postgres 9.5.1.
I am going to check this issue and post update in this thread later today.

**Comment by wjch-krl** [comment]
I have tested it on Ubuntu 14.10 with PostgreSQL 9.5.1 and everything is working well. 
I have installed Multicorn from newest github sources.

**Comment by ratheesh-kr** [comment]
Thanks for your Help... Its Working :)
